### ISSUE TITLE
New database connection on each request

### ISSUE THREAD

**Issue by tgdn** [remoteinterview/zero#115]
It seems every time a request is made a new database connection is made.

Is that the way it works? It would be nice having an example of how to connect to a different set of database (Postgres, MySQL, SQLite, Mongo, ...)

Doesn't the server keep on running with the connection being kept alive?

I might have misunderstood this. Do zero api calls work as serverless functions which are spawned upon each request?

Thanks for your help!

**Comment by asadm** [comment]
Zero does not spawn new node processes per request anymore. The earlier version did that but it has too many problems (memory usage, DB connection issues, session issues). Zero still does code-splitting per route (for API or pages both).
I think the best way to ensure only one instance of DB connection is to use `global` scope in your `connectDB()` method. Something like:

```js
async function connectDB(){
  if (!global._databaseConnection){
    await global._databaseConnection = await mysql.connect();
  }
  return global._databaseConnection
}

module.exports = connectDB
```

Does this make sense?

**Comment by tgdn** [comment]
It does make sense indeed :) 

I'll try it, thanks!
