### ISSUE TITLE
Do you plan to add Vue.js support?

### ISSUE THREAD

**Issue by dkarbayev** [remoteinterview/zero#13]
Just like react's jsx files, it would be nice to render `.vue` files for those who prefer Vue over React.

**Comment by kayandra** [comment]
I'm willing to submit the PR for Vue if it'll be accepted

**Comment by asadm** [comment]
We most def need Vue. It should be a separate handler like React, HTML, etc. If you would like to contribute, go ahead please!

Is `.vue` file the entrypoint to a vue app? If so, it will be easy:
- To add a new handler for a file type, you will need to first make change [here](https://github.com/remoteinterview/zero/blob/master/packages/core/lib/builder/buildManifest.js#L56) so it can list `.vue` files as `lambda:vue` type.

- Now you need to create a new handler package in this [directory](https://github.com/remoteinterview/zero/tree/master/packages) (see html handler for hints).

- And finally add the new handler to [this file](https://github.com/remoteinterview/zero/blob/master/packages/handlers-map/index.js).

**Comment by YajJackson** [comment]
I would be willing to help test whatever implementation gets thrown into review.

**Comment by kayandra** [comment]
@asadm righto, I'm pulling it in

**Comment by kayandra** [comment]
@asadm I followed the instructions [here](https://github.com/remoteinterview/zero/blob/master/CONTRIBUTING.md) and even tests on current master fails

**Comment by asadm** [comment]
@kayandra I was just merging and fixing #19. Should be fine now.

**Comment by asadm** [comment]
I have added basic support for Vue ([docs](https://github.com/remoteinterview/zero/blob/master/docs/vue/README.md)). 

I am trying to figure out how to modify `this.data` of the root Vue page during SSR, so I can inject query params and user session etc into it. [Relevant code here](https://github.com/remoteinterview/zero/blob/master/packages/handler-vue/renderer/index.js#L58). If only I can modify `App`'s data and add `props` variable to it. So then we can do `{{ url.query.id }}` in our vue page.

Also I have to figure out auto-dependency resolution for vue pages. So zero can auto-install any imported npm packages.

**Comment by asadm** [comment]
Vue support is now feature parity with React.
- Added auto-dependency resolution for `.vue` files.
- Added `asyncData` similar to Nuxt.js. [Docs](https://github.com/remoteinterview/zero/tree/master/docs/vue#fetching-api-data).
