### ISSUE TITLE
ESLint support

### ISSUE THREAD

**Issue by kuroisuna** [remoteinterview/zero#17]
I love this project, I'll be contributing as much as I can!

Since we do not have a `node_modules` how could we support a local instance of ESLint? (https://eslint.org/docs/user-guide/getting-started). And a `.eslintrc` config file.

For example:

###### .eslintrc.js
```js
module.exports = {
  extends: "airbnb",
};
```

BTW, similar to Prettier, this can be done on the Editor side (https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint for example).

**Comment by asadm** [comment]
Hello, Zero doesn’t *require* package.json and node_modules but you can add a basic package.json file with eslint as dependency and a npm script:

```json
{
    ...
    "scripts": {
        "pretest": "eslint --ignore-path .gitignore ."
    }
    ...
}
```

I think that should do it. 
Which reminds me, this project itself needs linting and clean up.
