### ISSUE TITLE
Are React Hooks supported?

### ISSUE THREAD

**Issue by pca2** [remoteinterview/zero#18]
Do you support React Hooks yet? I copied and pasted the [example code](https://reactjs.org/docs/hooks-intro.html) from the React website, however I was hit with an error:

```
Invariant Violation: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)

at /private/var/folders/k0/fqr3001s20n5gmnh5tt7jsxm0000gn/T/zeroservertmp/31fdc6488b585a0e4ab331793601476d705eb1ae/hook.jsx(Example):5
1   import React, { useState } from 'react';
2
3   function Example() {
4     // Declare a new state variable, which we'll call "count"
5     const [count, setCount] = useState(0);
6
7     return (
8       <div>
9         <p>You clicked {count} times</p>
10        <button onClick={() => setCount(count + 1)}>
```

**Comment by pavvo** [comment]
What React version do you use?

**Comment by pca2** [comment]
I don’t have React installed globally:

 npm list -g --depth=0

/usr/local/lib
├── axios@0.18.0
├── eslint@5.13.0
├── express-generator@4.16.0
├── ijavascript@5.0.20
├── mongodb-stitch-cli@1.1.0
├── npm@6.5.0
└── zero@1.0.8

**Comment by asadm** [comment]
This is probably a zero related bug. I am looking into it today.

**Comment by asadm** [comment]
It looks like the problem only happens during the [server render](https://github.com/remoteinterview/zero/blob/master/packages/handler-react/renderer/index.js). Because if I render a dumb component and then change it to use hooks, the HMR-updated component works fine in the browser.

**Comment by asadm** [comment]
I have fixed this in the latest version. Have a look!

**Comment by pca2** [comment]
👍  Looks good to me, thanks
