### ISSUE TITLE
Add Svelte support

### ISSUE THREAD

**Issue by bdougherty** [remoteinterview/zero#23]
Would be cool to have [Svelte](https://svelte.technology) support. Happy to attempt a PR once 3.0 is final, assuming it will be accepted.

**Comment by mblarsen** [comment]
> assuming it will be accepted

That depends on your PR as well :)

Go ahead. I would like Svelte (v3) support as well.

**Comment by asadm** [comment]
I would love to add support. One concerns:
Zero decides which handler/parser to send the file to based on the file extension ie. `.jsx`=> `handler-react`, `.js`=>`handler-js` etc. I wonder how we can differentiate between various js frameworks all saved as `.js` file. Maybe perform some AST?
This problem applies when trying to support any other JS frameworks.

**Comment by bdougherty** [comment]
@mblarsen ha yeah, I meant more if the project is open to adding additional framework support.

@asadm Svelte is going to officially use the `.svelte` extension soon (sveltejs/svelte#2067), so I don't think that will be an issue here.

**Comment by asadm** [comment]
Great. I am happy to assist with this once the extension is supported.

**Comment by LukasOchmann** [comment]
What about an first-line comment like `//react` or `//svelte` ...and as a fallback using the file extension.
Also an `//ignore` would be possible this way.

**Comment by brucou** [comment]
Svelte 3 is released!!

**Comment by asadm** [comment]
Awesome! I will look into this soon if no one else does.

**Comment by asadm** [comment]
I just finished Svelte 3 support for zero. [Docs](https://github.com/remoteinterview/zero/tree/master/docs/svelte)!

**Comment by brucou** [comment]
That's awesome!!
