### ISSUE TITLE
.zeroignore

### ISSUE THREAD

**Issue by coderafei** [remoteinterview/zero#25]
useful for libs/components/views... which no need expose

**Comment by tcmal** [comment]
Another option could be a header at the start of the file, i.e.

```
// zero: ignore
```

**Comment by wonderbeyond** [comment]
A more explicit way maybe introduce a manifest file that list all exportable files, other than ignoring files.

**Comment by aslafy-z** [comment]
I'd vote for a gitignore / dockerignore like. It's behavior can be reversed that way:
```
*/**

!this.js
!that.mdx
...
```
if needed.

I prefer this way so it sticks to the trends and does not force users to create a manifest. It's not called zero for nothing!

**Comment by asadm** [comment]
I have added support from `.zeroignore` in the latest beta. Anything listed in *ignore* will not be served publicly. You can give it a try: 
1. Install: `npm i -g zero@beta`
2. Add a `.zeroignore` file with:
```
components
```
3. Create a components folder and add a `.js` file.
4. Run zero, it will not serve any file from `/components/*`.

Feedback welcome!
