### ISSUE TITLE
using arrow function throws classProperties not enabled

### ISSUE THREAD

**Issue by xgenvn** [remoteinterview/zero#26]
Hi,

Currently I'm trying to use arrow function inside a react component, and got error during build:

```
 Support for the experimental syntax 'classProperties' isn't currently enabled
```

Is there anyway to support babel plugin such as "@babel/plugin-proposal-class-properties" so that `classProperties` can be used?

**Comment by asadm** [comment]
Thanks @Naaman-Saif!
I have pushed npm beta with this fix. `npm i -g zero@1.0.10-alpha.5`

**Comment by xgenvn** [comment]
I'm appreciated that PR caa26d0 is merged, however, it produced unnecessary changes than the functionalities it's adding. Please check again your coding guideline and format the files (I see changes in space to tab, multiline array declaration to single line, etc ...)

**Comment by asadm** [comment]
Thanks for the suggestions. I did add prettier on pre-commit hook after this. That should fix this for everyone.
