### ISSUE TITLE
TypeError "Cannot read property 'meta' of undefined"

### ISSUE THREAD

**Issue by Fil** [remoteinterview/zero#29]
I’m trying semiotic examples directly as .jsx files, and get this error:

```
 TypeError
Cannot read property 'meta' of undefined
```
the error apparently comes from
https://github.com/remoteinterview/zero/blob/b9a87e41a6a85553fe5e36d5e1587fca121f510b/packages/handler-react/renderer/index.js#L46

To reproduce go to https://semiotic.nteract.io/guides/line-chart, click on "copy full code" and paste as semiotic-example.jsx file in the zero folder.

(Is this an issue with zero or with semiotic?)

thank you

**Comment by Naaman-Saif** [comment]
Could you close zero, try again and let us know if it happens again?

**Comment by Fil** [comment]
I've even reinstalled it, but same.

⚡️ Zero v1.0.10-alpha.3 installed with
> npm install -g zero

Here's the content of my "docroot":
[zero-web.zip](https://github.com/remoteinterview/zero/files/2928516/zero-web.zip)

**Comment by asadm** [comment]
Looks like semiotic doesn't support rendering on server-side. Related issue: https://github.com/nteract/semiotic/issues/336

I will look into this further.

**Comment by asadm** [comment]
I did some fixes. Can you try the new beta: `npm install -g zero@1.0.10-alpha.6`

**Comment by Fil** [comment]
It logs this warning at every hit
⚠️ SSR didn't work for /semiot2. Some component might not be SSR compatible.
(which might be better spelled out as "Server Side Rendering"?)

but then it… works. Yay!
