### ISSUE TITLE
Support for Private Repos?

### ISSUE THREAD

**Issue by JasonHughes94** [remoteinterview/zero#33]
Hey,

Is there currently a way to pull from private repos?
We have a dependency on a repo that is private however from looking over the docs I can't see annything regarding how we would handle this.

Cheers,

Jason

**Comment by asadm** [comment]
By default zero installs the latest version from npm. You can override this by adding a `package.json` file with any dependency and it’s custom version, git url etc. Zero will install that instead.

**Comment by JasonHughes94** [comment]
Thanks for the speedy reply!

I'll give this a try and see how I get on.

Cheers,

Jason
