### ISSUE TITLE
Stuck on ✹ Generating manifest

### ISSUE THREAD

**Issue by FDiskas** [remoteinterview/zero#34]
If I tipe `zero something-stupid` it stuck:
```
$ zero dflgkjndfsglkjnf
⚡️ Zero v1.0.11
✺ Updating packagesnpm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 374 packages from 213 contributors and audited 3231 packages in 7.666s
found 0 vulnerabilities

✸ Generating manifest
```

Sys info:
```
node: v10.13.0
npm: 6.4.1
Kernel Version: 4.20.10-200.fc29.x86_64
Operating System: Fedora 29 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.55GiB
```

**Comment by FDiskas** [comment]
Also looks like its not good way to allow zero to scan directories like: `zero ../` :handbag:

**Comment by FDiskas** [comment]
And this one is the best
```bash
$ zero /
(node:12945) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, scandir '/boot/efi'
```

**Comment by asadm** [comment]
I think we can add a check if the folder exists and fail this gracefully. About `../` and `/`. Is there a guideline on what paths shouldn't be allowed? Isn't this the same as running other unix commands like `ls ../` or `rm ../`.

**Comment by FDiskas** [comment]
Thanks for response. About thous `/` In my opinion the the solution could be the max root directory is the current dir. :fist:

**Comment by FDiskas** [comment]
Actually what does second argument of `zero` program? I still cant run project if source code is within directory but execution of `zero` is in parent directory. I'm trying to run `zero` using npm scripts.

Still missing something like:
```zero --help```

**Comment by asadm** [comment]
The argument tells which directory to run the server in. So if you have:
Project/
 -www/
   -index.jsx

You can cd in Project and run `zero www`. 

You are right, I need to add `--help`.
