### ISSUE TITLE
Enhancement: some way to disallow including the bundle

### ISSUE THREAD

**Issue by abritinthebay** [remoteinterview/zero#40]
Using zero for basically 100% server side rendering it would be _great_ if I could stop the bundled JS from being included on the page as it dramatically increases page weight for zero benefit.

idea for a zero-config approach for this:

```
import {NoBundle} from "zero";

<NoBundle/>

// normal JSX/MDX/etc code goes here

```

Thoughts?

**Comment by asadm** [comment]
I think that's a good idea. How about this:
```jsx
export const config = {
  noBundling: true
}

export default ()=>(
  <div>Zero bundle</div>
```

Do you think it's better this way? Rather than importing a JSX component just so we avoid having *config*.

**Comment by abritinthebay** [comment]
That solution wouldn’t work for MDX though so... would still need a solution for that.

Effectively the imported component could do just that tho.

Maybe, to generalize:

```
import {Overrides} from “zero”;

<Overrides bundle={} someotherflag={} />
```

Overrides could effectively be a stateless function like so:

```
export const Overrides = (props)=>{
      // set higher scope stuff here from props
    return;
};
```

That way it could also be used in regular JS as:

```
Overrides({bundle: false});
```

Zero config, compatibility with all formats, flexibility for the future!

**Comment by asadm** [comment]
Actually it works with MDX too:
```jsx
# Heading
This is markdown

export const config = {
  noBundling: true
}
```

I understand the benefits that you listed of it being a component like `<Helmet />`. I will research pros and cons of both and keep this issue updated.

**Comment by abritinthebay** [comment]
Ah that's interesting. Didn't realize you could add JS exports to MDX.

Still not a huge fan of adding JS semantics to the files when not required however...
