### ISSUE TITLE
Missing content-type for JSX files

### ISSUE THREAD

**Issue by avo7** [remoteinterview/zero#41]
It would be nice, if `.jsx` files were served by zero with a `content-type: text/html` header.

It's required for example by Twitter to generate cards (https://cards-dev.twitter.com/validator) and adding it in a different way (`<meta>` tag, apache config, ...) is an ugly workaround.

**Comment by asadm** [comment]
You are right. Fixed in 67035814b0c8b01028c71e19b11c35b5bfe09868. Can you try it out in the latest beta: `npm install -g zero@beta`

**Comment by asadm** [comment]
Btw thanks for reporting this. It also fixed [zeroserver.io](https://zeroserver.io)'s twitter card. 

![twitter](https://i.imgur.com/EfPN1lf.png)

**Comment by avo7** [comment]
Tested it, works fine. Thanks for a really quick fix!
