### ISSUE TITLE
How to deliver client-side JavaScript?

### ISSUE THREAD

**Issue by usergenic** [remoteinterview/zero#44]
How to serve JS file meant for browser context only?

**Comment by usergenic** [comment]
I'm little confused as to the recommended way to serve a javascript file that's meant to run in the browser context instead as an express server route?

**Comment by usergenic** [comment]
Do you basically just import whatever you need into .jsx components and leave it at that?

**Comment by asadm** [comment]
Exactly. You can import any modules into jsx. And maybe invoke them in componentDidMount()? 

You can do the same in your html files by including them as `<script src...`. Zero will bundle and serve these as client-side scripts.
