### ISSUE TITLE
Add Access-Control header for CORS

### ISSUE THREAD

**Issue by FDiskas** [remoteinterview/zero#46]
Add Access-Control header for CORS 
currently if I request an endpoint done with zero I got
Access-Control-Allow-Origin error

**Comment by LukasOchmann** [comment]
try this:
`module.exports = (req, res) => {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  res.send("ok");
}`

**Comment by asadm** [comment]
You can add a common middleware to do that. [See this](https://zeroserver.io/blog/posts/express-middlewares)
