### ISSUE TITLE
API response not changing when code changes

### ISSUE THREAD

**Issue by reed1** [remoteinterview/zero#47]
As stated, so if I have api.js:

`module.exports = (req, res) => {
  res.send({
    text: "Place your Node.js API here."
  })
}`

then change the text to : "Bla bla", the response of /api is still "Place your Node.js API here.". I need to restart the server, is there anyway it can be hotreloaded too? thanks

**Comment by asadm** [comment]
Does it stay the same even after a refresh? That text should change on refresh. If not, can you tell me what version of zero are you on?

**Comment by hasahmed** [comment]
Same issue here.

**Comment by reed1** [comment]
@asadm ah yes, I should have said it doesn't change on refresh. Api endpoint usually returns json, thus no extra script / HMR code injected, what I mean is server side hotreload 

Strange it doesn't work a while ago, now I clean install zero@1.0.11 and it works... closing this, sorry to disturb..thx

**Comment by asadm** [comment]
@hasahmed can you see what version you are on?
