### ISSUE TITLE
Run first load

### ISSUE THREAD

**Issue by sonnht1409** [remoteinterview/zero#48]
I have current files structure 

```
+--- api
|        +--- v1 
|        |        +--- user.js (require db and redis-connector)
|        |        +--- classroom.js (require db and redis-connector)
+--- firs_load
|        +--- db-connector.js
|        +--- redis-connector.js
```

How do I make zero to load these files from `first_load` first instead of require them in each file from `v1`?

**Comment by asadm** [comment]
The way zero works, each file runs as a separate server so that means you will have to import these dependencies in each file. 

The reason for this is: It helps in reducing unused imports. Like zero doesn’t import React until a react file is executed. Same for Vue.js. So the server stays fast.
