### ISSUE TITLE
Server lifecycle events?

### ISSUE THREAD

**Issue by Whoaa512** [remoteinterview/zero#49]
My use case here is that in dev mode I'd like to be able to run:
```
var openBrowser = require('react-dev-utils/openBrowser')

if (openBrowser('http://localhost:3000')) {
  console.log('The browser tab has been opened!');
}
```

after the server has created the manifest. 

Essentially I'm looking for some sort of lifecycle hooks or events to run code before or after.

**Comment by asadm** [comment]
I think the only way to do this is by using zero from it's API. It returns a promise after which you can do additional stuff.

This example will run zero in `./www/` directory:

```js
const path = require("path");
const startServer = require("zero").server;
const openBrowser = require('react-dev-utils/openBrowser');


startServer(path.join(__dirname, "./www")).then(()=>{
  if (openBrowser('http://localhost:3000')) {
    console.log('The browser tab has been opened!');
  }
})

```
