### ISSUE TITLE
CSS and Sass

### ISSUE THREAD

**Issue by mvolkmann** [remoteinterview/zero#5]
Is it on the roadmap to add support for CSS and Sass files?

**Comment by asadm** [comment]
It's already supported. See https://github.com/remoteinterview/zero/tree/master/examples/react-basic-css

**Comment by mvolkmann** [comment]
Great! The reason I thought there were not supported is that they don't appear in the list at https://github.com/remoteinterview/zero/tree/master/docs#code-files.
