### ISSUE TITLE
Use yarn instead of npm 

### ISSUE THREAD

**Issue by Whoaa512** [remoteinterview/zero#53]
Couldn't find a way to force zero to use yarn to install packages

**Comment by asadm** [comment]
You are right. Zero uses npm as of now. The relevant code is [here](https://github.com/remoteinterview/zero/blob/master/packages/core/lib/builder/installPackages.js).

I have yet to explore this. Will Yarn make installing and boot any faster? If so, we can def go for this change.

**Comment by Whoaa512** [comment]
It can be faster in some cases, but I don't have benchmarks on hand. The main reason for me is that the package resolution algos are slightly different.

I ran into an issue where the latest npm was not able to resolve my package that I had installed via github with `yarn add whoaa512/jsx-pdf#58feebf`

I was able to workaround it by downgrading to npm 5.2.0 after following [this thread](https://github.com/npm/npm/issues/17858)

However this could have been avoided if I had the ability to use yarn or better yet if zero detected that I was using `yarn.lock` and automatically used yarn similar to how [sindresorhus/np](https://github.com/sindresorhus/np) works

I'm in a bit of a crunch mode at the moment but I'll probably try to circle back to this exploration in a few weeks.

**Comment by Naaman-Saif** [comment]
[](https://github.com/appleboy/npm-vs-yarn)

Benchmarks here do suggest that yarn is ~50%+ faster in terms of speed. We could migrate totally to yarn since both npm and yarn use package.json to create lock files and node_modules.

[](https://github.com/jonschlinkert/yarn-api)
This can be used in place of [](https://github.com/remoteinterview/zero/blob/d75feb25bbcbaf1fa4e1879ef145dd0a866b338c/packages/core/lib/builder/installPackages.js#L101)

**Comment by antoninadert** [comment]
I really like that npm is the main option for most developers. I wouldn't go to yarn if it was to leave npm completely.
For example there is overhead in installing yarn and learn differences between yarn and npm, which some people do not want to deal with, even if you win 50% of time when installing dependencies (which you shouldn't be doing often anyways !)

**Comment by Whoaa512** [comment]
Yea I agree with @antoninadert, my hope is that it would be an opt in deal.

**Comment by asadm** [comment]
Zero now comes with yarn as dependency in v1.1. User can still use `npm install` if they want but zero will use yarn and generate `yarn.lock` file. I think that solves this.
