### ISSUE TITLE
Access heroku config vars

### ISSUE THREAD

**Issue by emarchak** [remoteinterview/zero#56]
Firstly, thanks for making a great, simple server! I'm really enjoying using Zero. 

I'm hosting my React app on Heroku and hoping to store some API tokens in [their config vars](https://devcenter.heroku.com/articles/config-vars). The [Zero documentation recommends](https://github.com/remoteinterview/zero/blob/d0bbdf4f374dd2ecfd784af82cc18b3b47c7eeaa/docs/nodejs/README.md) that I use a `.env` file, which works fine locally but I wouldn't want to deploy it my server.

Is there a recommended way to access the config vars on the front end? It seems like I should be able to extend [`setupEnvVariables()`](https://github.com/remoteinterview/zero/blob/master/packages/core/lib/index.js#L19) if you'll accept a PR.

**Comment by asadm** [comment]
You should be able to access all your env variables as you would in nodejs `.js` files:
`process.env.GITHUB_USERNAME`. These aren't exposed to React `.jsx` files because that would expose them to your users. You can however pass them as props to your component like this:

```jsx
// index.jsx
import React from "react";

export default class extends React.Component {
  static async getInitialProps() {
    return {
        "username" : process.env.GITHUB_USERNAME
    }
  }

  render() {
    return <p>My github username: {this.props.username}</p>;
  }
}
```


Does that solve the problem?

**Comment by emarchak** [comment]
That helped a lot!

It ended up being that Heroku didn't provide any access to the env variables at all to the .jsx files. I ended up creating an express .js endpoint and handling it there. Which is more secure anyway. 

Thanks!
