### ISSUE TITLE
Can't load plain javascript without processing

### ISSUE THREAD

**Issue by mcoquet** [remoteinterview/zero#58]
I have a very simple example of trying to serve an html file that looks like : 

```HTML
<html lang="en">
<body>
<script type="module" src="/meow.mjs"> </script>
 Hellow world
</body>
</html>
```

and meow.mjs reads
```javascript
alert("boom")
```

Zero - as expected tries to bundle the js. Is there anyway we can avoid that behavior and , for some files or directories, just serve statically?

**Comment by asadm** [comment]
We don't yet have a way to ignore bundler for some paths. Is there a use case for this? ie. when bundling breaks something?

The above code is bundled and served correctly.

**Comment by mcoquet** [comment]
I don't believe its breaking. My use case is simply having a plain web page with some javascript that I would like to be served statically. Thanks!
