### ISSUE TITLE
Importing react-pdf throws classProperties error.

### ISSUE THREAD

**Issue by WriteCodeEveryday** [remoteinterview/zero#60]
This may be related to #26, and #27, but neither the regular or webpack imports work within zero server.

Does anyone have an alternative way to import PDFs and manipulate them that is compatible?

**Comment by WriteCodeEveryday** [comment]
This can be imported through parcel imports, but it appears this could be an issue in the future.

**Comment by asadm** [comment]
Sorry I didn't get time to look into this. But can you share a bit more on how you solved this?

**Comment by WriteCodeEveryday** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} React-pdf exports a regular export, a webpack configuration and a parcel config. The parcel config worked, all others failed                                                                                                                                                                        Sent via BlackBerry Hub+ Inbox for Android                                                                                                                                                                           From: notifications@github.comSent: May 18, 2019 8:07 AMTo: zero@noreply.github.comReply-to: reply@reply.github.comCc: lherr012@fiu.edu; state_change@noreply.github.comSubject: Re: [remoteinterview/zero] Importing react-pdf throws classProperties error. (#60)  Sorry I didn't get time to look into this. But can you share a bit more on how you solved this?
