### ISSUE TITLE
Routing Params broke with Version 1.0.17

### ISSUE THREAD

**Issue by DerLord** [remoteinterview/zero#63]
After upgrading to Version 1.0.17, the enhanced "Routing params" do not work anymore.
This means, trying to reach a non existing file `"/test"` resolves in a "not found" message instead of being handed the "index" file with the param `["test"]`.

This is fully reproducible.
Downgrading back to Version 1.0.16 resolves this.

**Comment by asadm** [comment]
Hello, the catch-all routes were causing a lot of confusion on which route is being handled by which file and didn't provide a way to handle error pages like 404. To improve this, we have made some changes to this feature [documented here](https://github.com/remoteinterview/zero#dynamic-routes-pretty-url-slugs). I think this method will cater to all older scenarios (like `/user/$userId`) and even more complex ones (like `$userId/messages/$msgId`). 

This obviously is a breaking change but changes should be minimal.

**Comment by DerLord** [comment]
Thanks for the really fast answer. I just held a presentation today regarding Zero and wondered why it stopped working as it did before. Sorry about that!
I'll close this issue.
