### ISSUE TITLE
Possibility to define a whitelist of files and folders to be routed

### ISSUE THREAD

**Issue by httpiago** [remoteinterview/zero#64]
For example, consider this project structure:

- components
  - ...
- pages
  - index.js
- api
  - middlewares
    - verifyJWT.js
  - users
    - create.js

And dev could tell to zero which folders he wants to be routed using arguments:

```bash
$ zero pages api
```

Interesting to remember that the .zeroignore file should still work to ignore files within the whitelist, for exemplo to ignore folder "middlewares" inside "api".

**Comment by asadm** [comment]
Missed this! 
So one possible workaround is to use the existing `.zeroignore` file in the following way:

```bash
# Ignore everything
*
# But descend into directories
!*/
# Recursively allow files under a folder
!/pages/**
!/api/**

# But also ignore a sub-sub folder
/api/middlewares/**
```

Does this solve the issue for your use case? Having a separate whitelist feature may get confusing.
