### ISSUE TITLE
Disable yarn install with CLI

### ISSUE THREAD

**Issue by themadcreator** [remoteinterview/zero#68]
Updating packages EVERY TIME the server runs can lead to all kinds of issues if dependencies break. Furthermore, it causes a completely unnecessary and long delay on startup.

After the initial install, I don't want the zero server to overwrite the dependencies I've set up. I just want it to render the content I point it at.

Please add a CLI option to disable this. At the very least this should never happen when `NODE_ENV=production`.

**Comment by asadm** [comment]
You are right. The long boot delay is annoying to me too. I am looking into ways to solve this and hopefully will solve it in next release or so.

**Comment by Bhavesh27** [comment]
on it

**Comment by asadm** [comment]
v1.1 solves this.
