### ISSUE TITLE
zero --version never ending yarn !

### ISSUE THREAD

**Issue by tmiele** [remoteinterview/zero#78]
I install zero globally with npm on Windows 10 and when I test zero and just after a zero --version and what the fuck a call to --version tag just for check the fresh install modify never ending build manifest :
````bash
zero --version
⚡️ Zero v1.0.19
⬇️  Updating packages
yarn install v1.19.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.0: The platform "win32" is incompatible with this module.
info "fsevents@2.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
Done in 97.84s.
\ Generating manifest```

**Comment by seeidea** [comment]
Me too, Check too many things every time you start

**Comment by asadm** [comment]
If I understand your question correctly, you are trying to check the version of zero with --version?

There is no `--version` or `-v` command. Zero ignores it and runs the server *on the current directory*.
