### ISSUE TITLE
Security: still an arbitrary file system leak

### ISSUE THREAD

**Issue by abritinthebay** [remoteinterview/zero#8]
Follow up to #3 

The fix right now will not work on windows, and while it's _better_, it still has flaws. It also, oddly, imports `path` twice. Which is a minor thing but a trivial optimization fix.

A better, and more bulletproof, solution is to resolve the app starting directory and the requested resource and see if the app directory is part of the resource requested.

For example:

```
const requestedPath = path.resolve(file);
const isSafePath = requestedPath.startsWith(process.env.BUILDPATH);
```

This way you will _always_ have a file that starts with the build path.

Either way - the current version is better, but not a fix.

**Comment by asadm** [comment]
Good idea, I [rewrote](946b31973e56171111d40a6abee84b3a8017a6ea) the static handler to just use `express.static`. Which has this protection built-in.
