### ISSUE TITLE
Bump React version to latest

### ISSUE THREAD

**Issue by asadm** [remoteinterview/zero#81]
Zero is using a bit older version of React. We need to update it to latest version. Off the top of my head:

- [ ] [Clone, install and run zero locally](https://github.com/remoteinterview/zero/blob/master/CONTRIBUTING.md#contributing-to-zero).
- [ ] Update in packages [here](https://github.com/remoteinterview/zero/blob/master/packages/common-deps/package.json), [here](https://github.com/remoteinterview/zero/blob/master/packages/handler-react/package.json).
- [ ] Run tests (`npm run test`) and see if all of them pass.
- [ ] Send PR :)

**Comment by zEduardofaria** [comment]
I'd like to take this one!

**Comment by asadm** [comment]
Go ahead!

**Comment by zEduardofaria** [comment]
Check #86

**Comment by asadm** [comment]
This one is still up for grabs.

**Comment by nkg447** [comment]
I would like to work on it.
